server.port=8081
spring.data.mongodb.uri=mongodb+srv://abhayrajrathi616_db_user:5EJ8QNwc437CHf7R@clusterccoffeeshop.8h2hctm.mongodb.net/coffee_shop?retryWrites=true&w=majority&appName=Clusterccoffeeshop
